### ISSUE TITLE
OpenReview link?

### ISSUE THREAD

**Issue by yoonholee** [a-tea-guy/ICON#1]
I'm quite interested in your method after seeing it on the WILDS leaderboard. Could you provide the openreview link, so I can read the paper? I couldn't find it anywhere.

**Comment by a-tea-guy** [comment]
Hi,

Thanks for your interest! The openreview link is not available yet. I will update you as soon as it becomes available.

Nick

**Comment by yoonholee** [comment]
Sounds good, thanks in advance!
